version: '3.1'  # Secrets are only available since this version of Docker Compose
services:
  orthanc:
    build: orthanc
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    environment:
      - VERBOSE_ENABLED="true"
      - VERBOSE_STARTUP="true"
      - ORTHANC__PYTHON_VERBOSE="true"

secrets:
  orthanc.json:
    file: orthanc/orthanc.configuration.json
